require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - Gemfile
    - Rakefile
    - db/**/*
    - bin/**/*
    - tmp/**/*
    - config/**/*
    - node_modules/**/*
    - spec/rails_helper.rb
    - test/**/*
    - vendor/bundle/**/*

Lint/MissingSuper:
  Exclude:
    - app/components/*_component.rb # not seen view_components call super

Lint/UselessAssignment:
  Exclude:
    - spec/components/comment_component_spec.rb

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - app/controllers/design_system_docs_controller.rb

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/StringConcatenation:
  Exclude:
    - spec/helpers/enum_helper_spec.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  Enabled: false
